/*
LÜTFEN  .DEV DOSYASINI KULLANARAK AÇINIZ
EÐER AKSÝ  YAPILIRSA PROGRAM ÇALIÞMAYACAK VE DERLENMEYECEKTÝR !
*/


/* 			UYGULAMA ILE ILGILI GENEL ACIKLAMALAR
	AD : EMRE 
	SOYAD : YAHYAOÐLU 
	OGRENCI NUMARASI : 210707024 
	BOLUM : BILGISAYAR MUHENDISLIGI ORGUN OGRETIM 
	DERSIN ADI VE KODU : NESNEYE YONELIK PROGRAMLAMA, BM104 
	DERSIN VERILDIGI AKADEMIK DONEM : BAHAR 2022 
	PROJE NUMARASI : PROJE1 
	DERSI VEREN OGRETIM UYESIENIN ADI : GULSAH TUMUKLU OZYER
*/

#include <iostream>
#include "BM104_210707024_Proje1.h"
using namespace std;

int main() {
    int q,w,e;
    cout << "Dizideki eleman sayisini giriniz : " << endl;
    cin >> q;
    BM104_210707024_Proje1 nsn(q,1,9);
    nsn.OyunOyna();
    return 0;
}

